# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-17 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailitem',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')], default=0),
        ),
    ]
