# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-19 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_app', '0003_auto_20190919_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
