# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-26 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_app', '0004_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailitem',
            name='body_word_count',
            field=models.CharField(blank=True, default='', max_length=1027, null=True),
        ),
        migrations.AlterField(
            model_name='emailitem',
            name='preview_word_count',
            field=models.CharField(blank=True, default='', max_length=1027, null=True),
        ),
        migrations.AlterField(
            model_name='emailitem',
            name='subject_word_count',
            field=models.CharField(blank=True, default='', max_length=1027, null=True),
        ),
    ]
