# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-26 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_app', '0005_auto_20190926_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailitem',
            name='body_word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailitem',
            name='preview_word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailitem',
            name='subject_word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
