# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-26 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_app', '0006_auto_20190926_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_username', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('from_email', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('to_email', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('subject_top_3', models.TextField(blank=True, default='', null=True)),
                ('preview_top_3', models.TextField(blank=True, default='', null=True)),
                ('body_top_3', models.TextField(blank=True, default='', null=True)),
                ('link_top_3', models.TextField(blank=True, default='', null=True)),
                ('full_link_top_3', models.TextField(blank=True, default='', null=True)),
                ('emoji_top_3', models.TextField(blank=True, default='', null=True)),
                ('average_word_count', models.IntegerField(blank=True, null=True)),
                ('median_word_count', models.IntegerField(blank=True, null=True)),
                ('high_word_count', models.IntegerField(blank=True, null=True)),
                ('low_word_count', models.IntegerField(blank=True, null=True)),
                ('body_word_count', models.IntegerField(blank=True, null=True)),
                ('average_emails_per_week', models.IntegerField(blank=True, null=True)),
                ('average_interval', models.IntegerField(blank=True, null=True)),
                ('longest_interval', models.IntegerField(blank=True, null=True)),
                ('first_date', models.DateTimeField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('email_sent_time', models.TextField(blank=True, null=True)),
                ('email_sent_day', models.TextField(blank=True, null=True)),
                ('average_images', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
